# Generated by Django 6.0.2 on 2026-02-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asatidz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('download_link', models.URLField()),
                ('keilmuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asatidz.keilmuan')),
            ],
        ),
        migrations.CreateModel(
            name='BabKitab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('youtube_link', models.URLField()),
                ('kitab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kajian.kitab')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('youtube_link', models.URLField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asatidz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asatidz.asatidzprofile')),
            ],
        ),
    ]
