# Generated by Django 6.0.2 on 2026-02-06 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BahtsulMasail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bahtsul', 'Bahtsul Masail'), ('muamalat', 'Muamalat'), ('quote', 'Quote')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bahtsul_masail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BahtsulReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('article', 'Article'), ('video', 'Video')], max_length=20)),
                ('link', models.URLField()),
                ('bahtsul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='bahtsul.bahtsulmasail')),
            ],
            options={
                'db_table': 'bahtsul_references',
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bahtsul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='bahtsul.bahtsulmasail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discussions',
                'ordering': ['created_at'],
            },
        ),
    ]
