# Generated by Django 6.0.2 on 2026-02-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuranSurah',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('total_ayat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuranAyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayat_number', models.IntegerField()),
                ('arab_text', models.TextField()),
                ('translation', models.TextField()),
                ('tafsir', models.TextField()),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.quransurah')),
            ],
        ),
    ]
