# Generated by Django 6.0.2 on 2026-02-06 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quran', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TahsinSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_start', models.IntegerField()),
                ('ayat_start', models.IntegerField()),
                ('surah_end', models.IntegerField()),
                ('ayat_end', models.IntegerField()),
                ('juz_start', models.IntegerField()),
                ('juz_end', models.IntegerField()),
                ('mode', models.CharField(choices=[('tahsin', 'Tahsin'), ('murojaah', 'Murojaah')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TahsinError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_note', models.TextField()),
                ('ayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.quranayat')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tahsin.tahsinsession')),
            ],
        ),
    ]
