# Generated by Django 6.0.2 on 2026-02-06 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
                ('bidang_keilmuan', models.CharField(max_length=100)),
                ('kode_room', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('link_kitab', models.URLField(blank=True, null=True)),
                ('jumlah_audiens', models.IntegerField(default=0)),
                ('mulai_pada', models.DateTimeField(auto_now_add=True)),
                ('asatidz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Live',
        ),
    ]
