# Generated by Django 6.0.2 on 2026-02-06 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_donasi', models.CharField(choices=[('infaq', 'Infaq Asatidz'), ('sodaqoh', 'Sodaqoh'), ('al_quran', 'Wakaf Al-Quran')], max_length=20)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bukti_transfer', models.ImageField(upload_to='donasi/bukti/')),
                ('catatan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=15)),
                ('tanggal_donasi', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
