# Generated by Django 6.0.2 on 2026-02-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoaHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('arab_text', models.TextField()),
                ('latin_text', models.TextField(blank=True, null=True)),
                ('translation', models.TextField()),
                ('fadhilah', models.TextField(blank=True, null=True)),
                ('audio_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'doa_harian',
                'ordering': ['-created_at'],
            },
        ),
    ]
