# Generated by Django 6.0.2 on 2026-02-07 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asatidz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asatidzprofile',
            name='photo',
        ),
    ]
