# Generated by Django 6.0.2 on 2026-02-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asatidz', '0002_remove_asatidzprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asatidzprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='asatidz/'),
        ),
    ]
