# Generated by Django 6.0.2 on 2026-02-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asatidz', '0003_asatidzprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asatidzprofile',
            name='photo',
        ),
    ]
