# Generated by Django 6.0.2 on 2026-02-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asatidz', '0004_remove_asatidzprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asatidzprofile',
            name='keilmuan',
        ),
        migrations.AddField(
            model_name='asatidzprofile',
            name='keilmuan',
            field=models.ManyToManyField(blank=True, to='asatidz.keilmuan'),
        ),
    ]
