# Generated by Django 6.0.2 on 2026-02-07 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asatidz', '0005_remove_asatidzprofile_keilmuan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asatidzprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='asatidz/'),
        ),
        migrations.RemoveField(
            model_name='asatidzprofile',
            name='keilmuan',
        ),
        migrations.AddField(
            model_name='asatidzprofile',
            name='keilmuan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asatidz.keilmuan'),
        ),
    ]
